# Generated by Django 4.2.30 on 2026-05-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_traces', models.PositiveIntegerField()),
                ('successful_traces', models.PositiveIntegerField()),
                ('failed_traces', models.PositiveIntegerField()),
                ('total_agent_text_words', models.PositiveIntegerField()),
                ('total_human_text_words', models.PositiveIntegerField()),
                ('total_human_messages', models.PositiveIntegerField()),
                ('total_session_duration_ms', models.PositiveBigIntegerField()),
                ('average_session_duration_ms', models.PositiveBigIntegerField()),
                ('median_session_duration_ms', models.PositiveBigIntegerField()),
                ('longest_session_duration_ms', models.PositiveBigIntegerField()),
                ('shortest_session_duration_ms', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
